![NASA](http://www.nasa.gov/sites/all/themes/custom/nasatwo/images/nasa-logo.svg)
![DEVELOP](../../DEVELOP_logo.png)

---

# NumPy

### Goddard Space Flight Center

#### September 28, 2016

# What is NumPy?

---

* Efficient array computing package in Python.
* Handles array manipulation and creation and indexing!
* Provides common mathematical operations for arrays.
* Faster than using __for__ loops! Use array operations whenever possible.

# Making Arrays

---

In [3]:
import numpy as np

li = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(type(li))

[1 2 3 4 5]
<type 'numpy.ndarray'>
<type 'list'>


* Basic array construct is a `ndarray` for `n`-dimensional arrays, but we can have 1-D arrays too.

    (__Note:__ You usually don't create an `ndarray` directly, but through the `array` method.)
    
* Behave like lists when they are 1-D.
* Biggest difference: all elements are of the same data type! This allows for much faster computation.

In [13]:
print(li[-1])
print(arr[-1])

# let's try to change these
li[3] = 'a string'
arr[3] = -1
print(li)
print(arr)

print(arr.dtype) # type for elements of array
arr = np.array([1.5, 2.5, 3.5, 4.5, 5.5, -6.5], dtype=np.uint8)
print(arr)
print(np.uint8(1.5))

5
5
[1, 2, 3, 'a string', 5]
[  1   2   3 255   5]
uint8
[  1   2   3   4   5 250]
1


Sometimes we know the size of the array, but we want the array filled with 0 or 1.

In [31]:
arr = np.ones((3,2))
#print(arr)
arr = np.zeros((6,2))
#print(arr)
arr = np.empty((2,5,2), dtype=np.float64)
print(arr)

#print(arr.shape)

[[[  2.21511805e-314   2.17293623e-314]
  [  2.21505631e-314   2.17298025e-314]
  [  2.12199579e-314   2.17089733e-314]
  [  1.27319747e-313   4.66094266e-309]
  [  1.62863271e-292   1.76125793e-312]]

 [[  6.42285340e-323   1.27319747e-313]
  [  1.27319747e-313   1.27319747e-313]
  [  1.27319747e-313   1.27319747e-313]
  [  4.44659081e-323   2.54639495e-313]
  [  7.41098469e-323   3.81959242e-313]]]


Or, maybe we want to create a linear or logarithmic grid space...

In [37]:
arr = np.linspace(-5, 5, 11, dtype=np.int64) # start, stop, num
print(arr)

arr = np.logspace(0, 10, num=10, base=10., dtype=np.int64) # base ** start, base ** stop
print(arr)

arr = np.arange(-5, 500, 3, float) # start, stop, increment
print(arr)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[          1          12         166        2154       27825      359381
     4641588    59948425   774263682 10000000000]
[  -5.   -2.    1.    4.    7.   10.   13.   16.   19.   22.   25.   28.
   31.   34.   37.   40.   43.   46.   49.   52.   55.   58.   61.   64.
   67.   70.   73.   76.   79.   82.   85.   88.   91.   94.   97.  100.
  103.  106.  109.  112.  115.  118.  121.  124.  127.  130.  133.  136.
  139.  142.  145.  148.  151.  154.  157.  160.  163.  166.  169.  172.
  175.  178.  181.  184.  187.  190.  193.  196.  199.  202.  205.  208.
  211.  214.  217.  220.  223.  226.  229.  232.  235.  238.  241.  244.
  247.  250.  253.  256.  259.  262.  265.  268.  271.  274.  277.  280.
  283.  286.  289.  292.  295.  298.  301.  304.  307.  310.  313.  316.
  319.  322.  325.  328.  331.  334.  337.  340.  343.  346.  349.  352.
  355.  358.  361.  364.  367.  370.  373.  376.  379.  382.  385.  388.
  391.  394.  397.  400.  403.  406.  4

# Multidimensional Arrays

---

In [42]:
arr = np.array([[0.2, 5.3],[7.4, 8.2]])
print(arr)
print(arr[:-1])

[[ 0.2  5.3]
 [ 7.4  8.2]]
[[ 0.2  5.3]]


# Array Operations

---

In [43]:
arr = np.array([[0.2, 5.3],[7.4, 8.2]])
b = 3*arr -1
print(b)

[[ -0.4  14.9]
 [ 21.2  23.6]]


In [44]:
print(arr.mean())
print(arr.std())

5.275
3.11558581971


# Reference Links

* [NumPy Reference](http://docs.scipy.org/doc/numpy/reference/)
* [Tentative NumPy Tutorial](http://scipy.github.io/old-wiki/pages/Tentative_NumPy_Tutorial.html)
* [for MATLAB users](http://mathesaurus.sourceforge.net/matlab-numpy.html)
* [for R users](http://mathesaurus.sourceforge.net/r-numpy.html)
* [NumPy for Biologists](http://people.duke.edu/~ccc14/pcfb/numerics.html)
* [SciPy 2012 Video](http://www.youtube.com/watch?v=3Fp1zn5ao2M)